### ISSUE TITLE
Make tricolour boring

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/tricolour#42]
See here: https://github.com/ska-sa/meerkathi/issues/529#issuecomment-508753263

Looks like the groovy colourful logo is making the output stream choke.

Suggest implementing a ``-boring`` option (see --Log-Boring in CubiCal and DDFacet), which disables all the fancy characters and colours. Much friendlier to batch mode.

**Comment by o-smirnov** [comment]
@IanHeywood reports this dreaded error again on the CHPC cluster:
```
--- Logging error ---
Traceback (most recent call last):
 File "logging/__init__.py", line 982, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 452:
ordinal not in range(128)
```
Running it inside a Stimela container, so maybe the issue belongs there, but reopening it here  just so it doesn't get lost.

**Comment by bennahugo** [comment]
https://github.com/ratt-ru/Stimela/issues/530

**Comment by bennahugo** [comment]
I even saw @sjperkins start to code in unicode which looked really interesting and scary at the same time!

**Comment by o-smirnov** [comment]
And do you think it is a coincidence that he had to take extended leave shortly after?
